### ISSUE TITLE
Do we really need to ignore yarn.lock?

### ISSUE THREAD

**Issue by barabadzhi** [udacity/reactnd-project-myreads-starter#20]
Hi, guys!

Here we are ignorring the `yarn.lock` file:
https://github.com/udacity/reactnd-project-myreads-starter/blob/29ba2f0984799d159da05f2f36748988cf52e052/.gitignore#L2

But this is a misuse of this file according the documentation:

> ... **consistent installs** across machines ...
> ... To do this Yarn **uses** a `yarn.lock` ...
[Yarn Docs](https://yarnpkg.com/lang/en/docs/yarn-lock/)

This is good to have .lock files checked-in for consistency and _speed_.

PS: Thanks for the course, its awesome. 🙂

**Comment by khw1031** [comment]
hmm. It is kind of weird. `.gitignore` shouldn't exclude `yarn.lock` file. 😃

**Comment by fpigeonjr** [comment]
👍  right the `.gitignore` from create-react-app includes:

```bash
.idea/
.vscode/
node_modules/
build
.DS_Store
*.tgz
my-app*
template/src/__tests__/__snapshots__/
lerna-debug.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
/.changelog
```

no mention of the `yarn.lock`

**Comment by veronikabenkeser** [comment]
Thank you for flagging! Fixed.
