### ISSUE TITLE
[help] update/mutate State on click option

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [udacity/reactnd-project-myreads-starter#24]
I'm trying to modify a specific book's shelf whenever an option tag is selected:

![ui](https://user-images.githubusercontent.com/4718827/29999399-b9515e18-9014-11e7-80a7-0cf8ade514bb.png)

The above code calls a custom `props` from a component `ListBooks` that looks like the following: 
`<ListBooks onChangeShelf={this.addTo}  books ={this.state.books}/>`

where `addTo` is a function which accepts 02 string inputs and is supposed to mutate my state:

![addto](https://user-images.githubusercontent.com/4718827/29999345-cd817cd0-9012-11e7-8a5c-92c2eb1bf3e7.png)

Issue: not sure that `$set` mutates my array according to log
PS: I'm using `immutability-helper` from npm

Any Hints?
A React Nano Student

**Comment by DDDDDanica** [comment]
There's an 'update' function in BookAPI to use?

**Comment by RanaivosonHerimanitra** [comment]
Yeah, solved it ;)
